CC=psp-gcc
AR=psp-ar
RANLIB=psp-ranlib
RM=rm -rf
PSPSDK=$(shell psp-config --pspsdk-path)
DEBUG_CFLAGS=-ggdb -gdwarf-2
RELEASE_CFLAGS=-O3
CFLAGS=-G0 $(RELEASE_CFLAGS) -Wall -DPSP -I$(PSPSDK)/include

all: libminizip.a

libminizip.a: ioapi.o unzip.o
	$(AR) cru $@ $?
	$(RANLIB) $@

clean:
	$(RM) *.o *.a
  